name: Docker Baseimage Builder

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    paths:
      - '.github/workflows/!baseimages.yml'
      - 'Dockerfile.debian11'
      - 'Dockerfile.focal'
      - 'zabuilder.sh'
      - 'zbuilder.sh'
  workflow_dispatch:

jobs:
  bullseye:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: build docker container
        env:
          HUB_NAME: ${{ secrets.DOCKER_NAME }}
          HUB_KEY: ${{ secrets.DOCKER_TOKEN }}
          CR_PAT: ${{ secrets.CR_PAT }}
        run: |
          echo $CR_PAT | docker login ghcr.io -u PrebuiltMPR --password-stdin
          docker build . -f Dockerfile.debian11 --pull --no-cache --tag ghcr.io/prebuiltmpr/mpr-builder:bullseye
          docker push ghcr.io/PrebuiltMPR/mpr-builder:bullseye


  focal:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: build docker container
        env:
          HUB_NAME: ${{ secrets.DOCKER_NAME }}
          HUB_KEY: ${{ secrets.DOCKER_TOKEN }}
          CR_PAT: ${{ secrets.CR_PAT }}
        run: |
          echo $CR_PAT | docker login ghcr.io -u PrebuiltMPR --password-stdin
          docker build . -f Dockerfile.focal --pull --no-cache --tag ghcr.io/PrebuiltMPR/mpr-builder:focal
          docker push ghcr.io/PrebuiltMPR/mpr-builder:focal
