name: ungoogled-chromium-linchrome-bin

on:
  schedule:
    - cron: '5 1 * * *'
  push:
    paths:
      - '.github/workflows/ungoogled-chromium-linchrome-bin.yml'
  workflow_dispatch:

jobs:
  bullseye:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: setup build folder
        run: |
          mkdir ~/build
          chmod 777 -R ~/build

      - name: build
        run: |
          docker run --name builder --user builder --net host ghcr.io/prebuiltmpr/mpr-builder:bullseye ungoogled-chromium-linchrome-bin
          docker cp builder:/results ~/build
          docker rm builder
          export FULL_PKGVER="$(cat ~/build/results/name.txt)"
          echo "FULL_PKGVER=$(cat ~/build/results/name.txt)" >> $GITHUB_ENV
          mv -v ~/build/results/${FULL_PKGVER} .
          sudo apt install python3 python3-pip
          pip3 install --upgrade cloudsmith-cli
      - name: upload
        run: |   
          cloudsmith push deb -k ${{ secrets.CLOUDSMITH_KEY }} prebuiltmpr/prebuiltmpr/debian/bullseye ./${FULL_PKGVER}

  focal:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: setup build folder
        run: |
          mkdir ~/build
          chmod 777 -R ~/build

      - name: build
        run: |
          docker run --name builder --user builder --net host ghcr.io/prebuiltmpr/mpr-builder:focal ungoogled-chromium-linchrome-bin
          docker cp builder:/results ~/build
          docker rm builder
          export FULL_PKGVER="$(cat ~/build/results/name.txt)"
          echo "FULL_PKGVER=$(cat ~/build/results/name.txt)" >> $GITHUB_ENV
          mv -v ~/build/results/${FULL_PKGVER} .
      - name: upload    
        run: |
          cloudsmith push deb -k ${{ secrets.CLOUDSMITH_KEY }} prebuiltmpr/prebuiltmpr/debian/focal ./${FULL_PKGVER}

